#!/usr/bin/env bash
# tools/gen_tls_cert.sh — Check and regenerate the Nebula32 TLS certificate.
#
# Called automatically during pico2_w firmware builds via CMakeLists.txt.
# Can also be run manually from the project root:
#   bash tools/gen_tls_cert.sh
#
# Outputs:
#   certs/server.key         — ECC P-256 private key (PEM, gitignored)
#   certs/server.crt         — Self-signed certificate (PEM, gitignored)
#   certs/server.crt.der     — Certificate in DER format (copy to SD card)
#   certs/server.key.der     — Private key in DER format (copy to SD card)
#   include/tls_cert.h       — C array fallback for firmware (gitignored, generated)
#
# SD card usage (priority over compiled-in cert):
#   mkdir -p /media/sdcard/certs
#   cp certs/server.crt.der /media/sdcard/certs/nebula32.crt.der
#   cp certs/server.key.der /media/sdcard/certs/nebula32.key.der
set -euo pipefail

CERT_DIR="certs"
CERT_PEM="$CERT_DIR/server.crt"
KEY_PEM="$CERT_DIR/server.key"
CERT_DER="$CERT_DIR/server.crt.der"
KEY_DER="$CERT_DIR/server.key.der"
HEADER="include/tls_cert.h"
DAYS_VALID=3650       # 10 years
CHECK_DAYS=30         # regenerate if expiring within this window

if ! command -v openssl &>/dev/null; then
    echo "[CERT] Warning: openssl not found — using existing $HEADER" >&2
    if [ ! -f "$HEADER" ]; then
        echo "[CERT] ERROR: $HEADER missing and openssl unavailable." >&2
        echo "[CERT]   Install openssl, then re-run: bash tools/gen_tls_cert.sh" >&2
        exit 1
    fi
    exit 0
fi

mkdir -p "$CERT_DIR"

# Check whether the current cert is valid for at least CHECK_DAYS more days.
NEED_REGEN=0
if [ ! -f "$CERT_PEM" ]; then
    echo "[CERT] No certificate found — generating new one..."
    NEED_REGEN=1
elif ! openssl x509 -checkend $((CHECK_DAYS * 86400)) -noout -in "$CERT_PEM" >/dev/null 2>&1; then
    echo "[CERT] Certificate expires within $CHECK_DAYS days — regenerating..."
    NEED_REGEN=1
fi

if [ "$NEED_REGEN" -eq 1 ]; then
    # Generate ECC P-256 private key.
    openssl ecparam -genkey -name prime256v1 -noout -out "$KEY_PEM"

    # Self-signed certificate — 10 years, SAN for common local hostnames.
    openssl req -new -x509 \
        -key "$KEY_PEM" -out "$CERT_PEM" \
        -days "$DAYS_VALID" \
        -subj "/CN=nebula32.local/O=Nebula32 ODE" \
        -addext "subjectAltName=DNS:nebula32.local,DNS:cd32ode.local"

    # DER conversion for SD card installation.
    openssl x509 -in "$CERT_PEM" -outform DER -out "$CERT_DER"
    openssl ec  -in "$KEY_PEM"  -outform DER -out "$KEY_DER" 2>/dev/null

    echo "[CERT] New certificate generated ($DAYS_VALID days, CN=nebula32.local)"
    echo "[CERT] To use a custom cert on your Nebula32, copy the DER files to the SD card:"
    echo "[CERT]   cp $CERT_DER <sdcard>/certs/nebula32.crt.der"
    echo "[CERT]   cp $KEY_DER  <sdcard>/certs/nebula32.key.der"
fi

# Regenerate include/tls_cert.h if the cert DER is newer than the header
# (or if the header is missing).
if [ ! -f "$HEADER" ] || [ "$CERT_DER" -nt "$HEADER" ]; then
    if ! command -v xxd &>/dev/null; then
        echo "[CERT] Warning: xxd not found — cannot generate $HEADER" >&2
        exit 0
    fi

    echo "[CERT] Updating $HEADER..."

    # xxd -i names variables by replacing dots in the filename with underscores.
    # server.crt.der → server_crt_der[] / server_crt_der_len
    # server.key.der → server_key_der[] / server_key_der_len
    CERT_VAR="server_crt_der"
    KEY_VAR="server_key_der"

    {
        printf '/* tls_cert.h — generated by tools/gen_tls_cert.sh; do not edit */\n'
        printf '/* Compiled-in fallback used when SD card cert is absent.        */\n'
        printf '#pragma once\n\n'

        # Certificate array — renamed to match wolfSSL API convention.
        (cd "$CERT_DIR" && xxd -i server.crt.der) \
          | sed "s/^unsigned char ${CERT_VAR}\[/static const unsigned char server_ecc_der_256[/" \
          | sed "s/^unsigned int ${CERT_VAR}_len/static const unsigned long sizeof_server_ecc_der_256/"

        printf '\n'

        # Private key array.
        (cd "$CERT_DIR" && xxd -i server.key.der) \
          | sed "s/^unsigned char ${KEY_VAR}\[/static const unsigned char ecc_key_der_256[/" \
          | sed "s/^unsigned int ${KEY_VAR}_len/static const unsigned long sizeof_ecc_key_der_256/"

    } > "$HEADER"

    echo "[CERT] $HEADER updated."
fi
