// =============================================================================
// webserver.c — HTTP Web Interface for Disc Selection
// =============================================================================
//
// Implements a minimal HTTP/1.1 server using lwIP TCP/IP stack (bundled with
// pico_cyw43_arch_lwip_poll) on the Pico 2 W's CYW43439 WiFi chip.
//
// Uses poll-mode lwIP (no RTOS, no threads) — webserver_poll() must be
// called regularly from the Core 0 main loop.
//
// Architecture:
//   One TCP listener on port 80.
//   Each connection is handled synchronously (accept → read → respond → close).
//   Connections are NOT kept-alive (Connection: close) for simplicity.
//   Cover art JPEGs are read from the SD card and streamed in 512-byte chunks.
//
// Memory:
//   A single 2 KB response buffer handles all non-file responses.
//   File serving uses a 512-byte SD card read buffer (FatFS cluster size).
//
// IMPORTANT: All webserver code runs on Core 0 only.
//            Core 1 is the real-time bus handler and is never involved.
// =============================================================================

#include "webserver.h"
#include "logger.h"
#include "sd_card_api.h"
#include "fw_update.h"
#include "disc_image.h"   // MAX_PATH_LEN
#include "cd_types.h"
#include "commo_bridge.h" // commo_bridge_get_drive_state()

// Pico W WiFi + lwIP headers
#include "pico/stdlib.h"
#ifdef PICO_CYW43_SUPPORTED
#include "pico/rand.h"    // get_rand_32() for fw_token generation
#include "pico/cyw43_arch.h"
#include "lwip/tcp.h"
#include "lwip/pbuf.h"
#include "lwip/ip4_addr.h"

// wolfSSL TLS — WOLFSSL_USER_SETTINGS routes to include/user_settings.h.
// Host test builds stub out the wolfSSL API so webserver.c compiles without
// the library installed. Real behaviour is firmware-only.
#ifndef WEBSERVER_TEST_BUILD
#ifndef WOLFSSL_USER_SETTINGS
#define WOLFSSL_USER_SETTINGS
#endif
#include <wolfssl/wolfcrypt/settings.h>
#include <wolfssl/ssl.h>
#include "tls_cert.h"              // server_ecc_der_256 / ecc_key_der_256 (generated by tools/gen_tls_cert.sh)
#else /* WEBSERVER_TEST_BUILD — wolfSSL compile-time stubs */
typedef struct wolfssl_t WOLFSSL;
typedef struct wolfssl_ctx_t WOLFSSL_CTX;
#define WOLFSSL_SUCCESS            1
#define WOLFSSL_FATAL_ERROR       (-1)
#define WOLFSSL_ERROR_WANT_READ   (-2)
#define WOLFSSL_ERROR_WANT_WRITE  (-3)
#define SSL_FILETYPE_ASN1          2
static inline void wolfSSL_Init(void) {}
static inline int wolfSSL_SetAllocators(void *mf, void *ff, void *rf)
    { (void)mf;(void)ff;(void)rf; return 0; }
static inline WOLFSSL_CTX *wolfTLSv1_3_server_method(void) { return NULL; }
static inline WOLFSSL_CTX *wolfSSL_CTX_new(WOLFSSL_CTX *m) { (void)m; return NULL; }
static inline void wolfSSL_CTX_free(WOLFSSL_CTX *c) { (void)c; }
static inline int wolfSSL_CTX_use_certificate_buffer(WOLFSSL_CTX *c,
    const unsigned char *b, long l, int f)
    { (void)c;(void)b;(void)l;(void)f; return WOLFSSL_SUCCESS; }
static inline int wolfSSL_CTX_use_PrivateKey_buffer(WOLFSSL_CTX *c,
    const unsigned char *b, long l, int f)
    { (void)c;(void)b;(void)l;(void)f; return WOLFSSL_SUCCESS; }
static inline WOLFSSL *wolfSSL_new(WOLFSSL_CTX *c) { (void)c; return NULL; }
static inline void wolfSSL_free(WOLFSSL *s) { (void)s; }
static inline int wolfSSL_accept(WOLFSSL *s) { (void)s; return WOLFSSL_SUCCESS; }
static inline int wolfSSL_read(WOLFSSL *s, void *b, int l) { (void)s;(void)b;(void)l; return 0; }
static inline int wolfSSL_write(WOLFSSL *s, const void *b, int l) { (void)s;(void)b; return l; }
static inline int wolfSSL_get_error(WOLFSSL *s, int r) { (void)s;(void)r; return 0; }
static inline int wolfSSL_SetIO_LwIP(WOLFSSL *s, void *p,
    void *rf, void *sf, void *a) { (void)s;(void)p;(void)rf;(void)sf;(void)a; return 0; }
// Cert buffer stubs (normally from <wolfssl/certs_test.h>)
static const unsigned char *server_ecc_der_256 = NULL;
static const unsigned long sizeof_server_ecc_der_256 = 0;
static const unsigned char *ecc_key_der_256 = NULL;
static const unsigned long sizeof_ecc_key_der_256 = 0;
#endif /* !WEBSERVER_TEST_BUILD */
#endif /* PICO_CYW43_SUPPORTED */
#include "ff.h"     // FatFS for cover art serving

#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include <stdlib.h>

#ifdef PICO_CYW43_SUPPORTED


// ---------------------------------------------------------------------------
// External state from main.c
// ---------------------------------------------------------------------------
extern char     s_image_paths[][MAX_PATH_LEN];
extern uint32_t s_image_count;

// ---------------------------------------------------------------------------
// WiFi credentials (read from nebula32.cfg)
// ---------------------------------------------------------------------------
static char s_ssid[WS_SSID_MAX]   = "";
static char s_pass[WS_PASS_MAX]   = "";
static char s_host[WS_HOST_MAX]   = WS_DEFAULT_HOSTNAME;
static char s_ip_str[16]          = "";
static bool s_running             = false;
// 32-char hex token loaded from nebula32.cfg — required to authorise firmware flash
static char s_fw_token[33]        = "";

// ---------------------------------------------------------------------------
// Pending load request from web interface
// ---------------------------------------------------------------------------
static volatile bool     s_load_pending = false;
static volatile uint32_t s_load_index   = 0;
static volatile uint32_t s_loaded_index = 0;   // Currently loaded disc

// ---------------------------------------------------------------------------
// Pending page-change request from web interface
// ---------------------------------------------------------------------------
static volatile bool s_page_request = false;
static volatile int  s_page_delta   = 0;   // +1 = next, -1 = prev

// ---------------------------------------------------------------------------
// Pending carousel / playlist request from web interface (Phase 3b)
// ---------------------------------------------------------------------------
static volatile bool s_carousel_request  = false;
static volatile int  s_carousel_delta    = 0;   // +1 = next, -1 = prev
static volatile bool s_playlist_request  = false;
static char          s_playlist_name[32] = {0}; // "" = all discs

// ---------------------------------------------------------------------------
// Current page position (set by main.c via webserver_set_page_info)
// ---------------------------------------------------------------------------
static uint32_t s_ws_page_offset = 0;
static uint32_t s_ws_page_count  = 0;
static uint32_t s_ws_total_count = 0;

// ---------------------------------------------------------------------------
// TCP listener state
// ---------------------------------------------------------------------------
static struct tcp_pcb *s_listener = NULL;

// Per-connection context
typedef struct {
    char     request[1024];    // Accumulate incoming HTTP request
    int      req_len;
    bool     headers_done;
    bool     in_use;           // Pool slot occupancy flag
    // TLS state (WOLFSSL_LWIP_NATIVE)
    WOLFSSL *ssl;              // Per-connection TLS session
    bool     tls_ready;        // true after wolfSSL_accept() succeeds
    char     resp_buf[4096];   // Per-connection response buffer (avoids shared-static race)
} http_conn_t;

// Shared TLS context (loaded once in webserver_init)
static WOLFSSL_CTX *s_tls_ctx = NULL;

// Static pool — avoids repeated heap fragmentation on an RTOS-less embedded target.
// The web page auto-refreshes every 5 seconds; 3 slots covers normal concurrent use.
#define HTTP_CONN_POOL_SIZE 3
static http_conn_t s_conn_pool[HTTP_CONN_POOL_SIZE];

static http_conn_t *conn_alloc(void) {
    for (int i = 0; i < HTTP_CONN_POOL_SIZE; i++) {
        if (!s_conn_pool[i].in_use) {
            memset(&s_conn_pool[i], 0, sizeof(s_conn_pool[i]));
            s_conn_pool[i].in_use = true;
            return &s_conn_pool[i];
        }
    }
    return NULL;
}

static void conn_free(http_conn_t *conn) {
    if (!conn) return;
    if (conn->ssl) {
        wolfSSL_free(conn->ssl);
        conn->ssl = NULL;
    }
    conn->in_use = false;
}

// ---------------------------------------------------------------------------
// Load WiFi credentials from the logger config (parsed once from nebula32.cfg)
// ---------------------------------------------------------------------------
static void read_wifi_config(void) {
    const logger_config_t *cfg = logger_get_config();
    strncpy(s_ssid, cfg->wifi_ssid,     sizeof(s_ssid));
    s_ssid[sizeof(s_ssid) - 1] = '\0';
    strncpy(s_pass, cfg->wifi_password, sizeof(s_pass));
    s_pass[sizeof(s_pass) - 1] = '\0';
    if (cfg->wifi_hostname[0] != '\0') {
        strncpy(s_host, cfg->wifi_hostname, sizeof(s_host));
        s_host[sizeof(s_host) - 1] = '\0';
    }
    strncpy(s_fw_token, cfg->fw_token, sizeof(s_fw_token));
    s_fw_token[sizeof(s_fw_token) - 1] = '\0';

    // S2: reject fw_token values that aren't exactly 32 lowercase hex chars.
    // A malformed token could be injected raw into the JS string in build_html_page();
    // clearing it here forces regeneration of a safe token via generate_and_save_token().
    {
        bool valid = (strlen(s_fw_token) == 32);
        for (int i = 0; valid && i < 32; i++) {
            char c = s_fw_token[i];
            if (!((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')))
                valid = false;
        }
        if (!valid)
            s_fw_token[0] = '\0';
    }
}

// ---------------------------------------------------------------------------
// Firmware-flash token helpers
// ---------------------------------------------------------------------------

// Append "fw_token = <hex32>\n" to nebula32.cfg and update s_fw_token in-place.
// Called once from webserver_init() when no token is found in the config file.
#ifndef WEBSERVER_TEST_BUILD
static void generate_and_save_token(void) {
    // Build 32-char hex token from four 32-bit hardware RNG words
    uint32_t r[4];
    r[0] = get_rand_32(); r[1] = get_rand_32();
    r[2] = get_rand_32(); r[3] = get_rand_32();
    snprintf(s_fw_token, sizeof(s_fw_token),
             "%08lx%08lx%08lx%08lx",
             (unsigned long)r[0], (unsigned long)r[1],
             (unsigned long)r[2], (unsigned long)r[3]);

    // S5: check whether a fw_token key already exists (even if empty) before
    // appending.  A blank value in the config causes s_fw_token to be empty on
    // load, triggering this function, which would otherwise append a second key
    // and grow the file unboundedly across reboots.
    bool key_exists = false;
    {
        FIL fr;
        if (f_open(&fr, "0:/nebula32.cfg", FA_READ) == FR_OK) {
            char scan_line[64];
            while (f_gets(scan_line, sizeof(scan_line), &fr)) {
                char *p = scan_line;
                while (*p == ' ' || *p == '\t') p++;
                if (strncmp(p, "fw_token", 8) == 0) { key_exists = true; break; }
            }
            f_close(&fr);
        }
    }

    if (!key_exists) {
        FIL f;
        if (f_open(&f, "0:/nebula32.cfg", FA_OPEN_APPEND | FA_WRITE) == FR_OK) {
            char line[48];
            int  len = snprintf(line, sizeof(line), "fw_token = %s\n", s_fw_token);
            UINT bw;
            f_write(&f, line, (UINT)len, &bw);
            f_close(&f);
            printf("[WEB] Generated fw_token and saved to nebula32.cfg\n");
        } else {
            printf("[WEB] Warning: could not save fw_token to nebula32.cfg\n");
        }
    }
}
#endif // WEBSERVER_TEST_BUILD

// Extract the token value supplied by the HTTP client.
// Checks (in order): X-FW-Token header, then ?token= query string in url_path.
// Writes into out[outsz]; always NUL-terminates.
static void extract_request_token(const char *req, const char *url_path,
                                  char *out, size_t outsz) {
    out[0] = '\0';
    if (outsz == 0) return;

    // 1. Check X-FW-Token header
    const char *hdr = strstr(req, "\r\nX-FW-Token: ");
    if (hdr) {
        hdr += sizeof("\r\nX-FW-Token: ") - 1;
        size_t i = 0;
        while (hdr[i] && hdr[i] != '\r' && hdr[i] != '\n' && i < outsz - 1) {
            out[i] = hdr[i];
            i++;
        }
        out[i] = '\0';
        if (out[0] != '\0') return;
    }

    // 2. Check ?token= query string
    const char *qs = strchr(url_path, '?');
    if (!qs) return;
    qs++;
    const char *tok = strstr(qs, "token=");
    if (!tok) return;
    tok += sizeof("token=") - 1;
    size_t i = 0;
    while (tok[i] && tok[i] != '&' && tok[i] != '#' && i < outsz - 1) {
        out[i] = tok[i];
        i++;
    }
    out[i] = '\0';
}

// ---------------------------------------------------------------------------
// HTML page generation
// ---------------------------------------------------------------------------
// The HTML is generated dynamically so it always reflects the current
// disc list and loaded state.  All CSS is inline so no external files
// are needed.  The page auto-refreshes every 5 seconds.

// Filename without extension from a full path
static const char *basename_no_ext(const char *path, char *buf, int bufsz) {
    const char *slash = strrchr(path, '/');
    const char *name  = slash ? slash + 1 : path;
    strncpy(buf, name, bufsz - 1);
    buf[bufsz - 1] = '\0';
    char *dot = strrchr(buf, '.');
    if (dot) *dot = '\0';
    return buf;
}

// Escape HTML special characters (<, >, &, ", ') into a caller-supplied buffer.
// Returns the number of bytes written (not counting the NUL terminator).
static int html_escape(char *out, int outsz, const char *in) {
    int n = 0;
    for (const char *p = in; *p; p++) {
        const char *esc;
        int elen;
        switch (*p) {
            case '&':  esc = "&amp;";  elen = 5; break;
            case '<':  esc = "&lt;";   elen = 4; break;
            case '>':  esc = "&gt;";   elen = 4; break;
            case '"':  esc = "&quot;"; elen = 6; break;
            case '\'': esc = "&#39;";  elen = 5; break;
            default:   esc = NULL;     elen = 1; break;
        }
        if (esc) {
            if (n + elen >= outsz - 1) break;
            memcpy(out + n, esc, elen);
            n += elen;
        } else {
            if (n >= outsz - 1) break;
            out[n++] = *p;
        }
    }
    out[n] = '\0';
    return n;
}

// Escape a string for safe embedding in a JSON string value.
// Escapes " and \ per RFC 8259; skips control chars (illegal in JSON strings).
static int json_escape(char *out, int outsz, const char *in) {
    int n = 0;
    for (const char *p = in; *p && n < outsz - 1; p++) {
        if (*p == '"' || *p == '\\') {
            if (n + 2 >= outsz - 1) break;
            out[n++] = '\\'; out[n++] = *p;
        } else if ((unsigned char)*p >= 0x20) {
            out[n++] = *p;
        }
        // control chars silently dropped
    }
    out[n] = '\0';
    return n;
}

static bool cover_exists(const char *image_path, char *cover_path_out, int outsz) {
    char base[MAX_PATH_LEN];
    basename_no_ext(image_path, base, sizeof(base));

    // Hard-cap the calculation. By subtracting 16, we leave plenty of 
    // guaranteed compile-time overhead for "0:/covers/" and ".jpeg" / ".png"
    int max_base_len = outsz - 16; 
    if (max_base_len < 0) {
        max_base_len = 0;
    }

    // 1. Try covers/ directory with EXT1
    // Adding an inline check directly in the snprintf argument forces GCC to recognize the absolute ceiling.
    snprintf(cover_path_out, outsz, "%s%.*s%s", WS_COVERS_DIR, 
             (max_base_len < outsz) ? max_base_len : 0, base, WS_COVER_EXT1);
    if (f_stat(cover_path_out, NULL) == FR_OK) return true;

    // 2. Try covers/ directory with EXT2
    snprintf(cover_path_out, outsz, "%s%.*s%s", WS_COVERS_DIR, 
             (max_base_len < outsz) ? max_base_len : 0, base, WS_COVER_EXT2);
    if (f_stat(cover_path_out, NULL) == FR_OK) return true;

    // Clear output buffer completely if no file was found
    if (outsz > 0) {
        cover_path_out[0] = '\0';
    }
    return false;
}


// Drive state name — aligned with drive_state_t (DRIVE_IDLE=0)
static const char *state_name(int state) {
    switch (state) {
        case 0: return "IDLE";    case 1: return "SPINUP";
        case 2: return "READY";   case 3: return "SEEKING";
        case 4: return "READING"; case 5: return "PLAYING";
        case 6: return "PAUSED";  case 7: return "ERROR";
        default: return "UNKNOWN";
    }
}

// SD card space via f_getfree. Returns false if the volume is not mounted.
static bool sd_get_space(uint64_t *used_out, uint64_t *total_out) {
    FATFS *fs;
    DWORD  fre_clust;
    if (f_getfree("0:", &fre_clust, &fs) != FR_OK) return false;
    uint64_t clust_bytes = (uint64_t)fs->csize * 512;
    uint64_t total       = (uint64_t)(fs->n_fatent - 2) * clust_bytes;
    uint64_t free_bytes  = (uint64_t)fre_clust * clust_bytes;
    *total_out = total;
    *used_out  = total - free_bytes;
    return true;
}

// Human-readable byte count: "X.X GB", "X.X MB", or "XXX KB"
static void fmt_bytes(char *buf, int bufsz, uint64_t bytes) {
    if (bytes >= (uint64_t)1024 * 1024 * 1024)
        snprintf(buf, bufsz, "%.1f GB", (double)bytes / (1024.0 * 1024 * 1024));
    else if (bytes >= (uint64_t)1024 * 1024)
        snprintf(buf, bufsz, "%.1f MB", (double)bytes / (1024.0 * 1024));
    else
        snprintf(buf, bufsz, "%lu KB", (unsigned long)(bytes / 1024));
}

// ---------------------------------------------------------------------------
// Cover art path cache — avoids up to 3 f_stat calls per image per HTML render
// ---------------------------------------------------------------------------
// Populated on demand and invalidated when the disc list changes.
// Sentinel: s_cover_cache[i][0] == '\1' means checked and not found.
#define WS_MAX_IMAGES 32
static char s_cover_cache[WS_MAX_IMAGES][256];
static bool s_cover_cache_valid = false;

static void refresh_cover_cache(void) {
    uint32_t n = s_image_count < WS_MAX_IMAGES ? s_image_count : WS_MAX_IMAGES;
    for (uint32_t i = 0; i < n; i++) {
        char path[256] = "";
        if (cover_exists(s_image_paths[i], path, sizeof(path)))
            strncpy(s_cover_cache[i], path, sizeof(s_cover_cache[i]));
        else
            s_cover_cache[i][0] = '\1';  // sentinel: checked, not found
    }
    s_cover_cache_valid = true;
}

// Generate the main HTML page into a dynamically allocated string.
// Caller must free() the returned pointer.
static char *build_html_page(void) {
    // We build into a large static buffer (stack is too small for this)
    static char html[32768];
    int pos = 0;

// Guard against pos going negative or past the buffer end before each write.
// Without this, sizeof(html)-pos underflows to a huge size_t when pos>=32768,
// causing snprintf to write well past the array boundary.
#define HCAT(fmt, ...) do { \
    int _rem = (int)sizeof(html) - pos - 1; \
    if (_rem > 0) { \
        int _n = snprintf(html + pos, (size_t)(_rem + 1), fmt, ##__VA_ARGS__); \
        if (_n > 0) pos += (_n < _rem ? _n : _rem); \
    } \
} while (0)

    HCAT("HTTP/1.1 200 OK\r\n"
         "Content-Type: text/html; charset=utf-8\r\n"
         "Connection: close\r\n"
         "Cache-Control: no-cache\r\n\r\n");

    HCAT("<!DOCTYPE html><html lang='en'><head>"
         "<meta charset='UTF-8'>"
         "<meta name='viewport' content='width=device-width,initial-scale=1'>"
         "<meta http-equiv='refresh' content='5'>"
         "<title>Nebula32 — Disc Selector</title>"
         "<style>"
         "body{font-family:system-ui,sans-serif;background:#1a1a2e;color:#e0e0e0;"
              "margin:0;padding:16px}"
         "h1{color:#c8a000;font-size:1.4rem;margin:0 0 4px 0}"
         ".subtitle{color:#888;font-size:.85rem;margin-bottom:20px}"
         ".status{background:#16213e;border-radius:8px;padding:12px 16px;"
                 "margin-bottom:20px;display:flex;gap:20px;flex-wrap:wrap;"
                 "border:1px solid #0f3460}"
         ".status-item{display:flex;flex-direction:column}"
         ".status-label{font-size:.72rem;color:#888;text-transform:uppercase;"
                        "letter-spacing:.05em}"
         ".status-value{font-size:1rem;font-weight:600;color:#c8a000}"
         ".grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));"
               "gap:16px}"
         ".disc{background:#16213e;border-radius:10px;padding:12px;cursor:pointer;"
               "border:2px solid transparent;transition:.15s;text-align:center;"
               "position:relative}"
         ".disc:hover{border-color:#c8a000;background:#1e2a4a}"
         ".disc.loaded{border-color:#2ecc71;background:#0d2b1e}"
         ".disc-cover{width:160px;height:160px;object-fit:cover;border-radius:6px;"
                     "background:#0f3460;display:block;margin:0 auto 10px}"
         ".disc-cover-svg{width:160px;height:160px;border-radius:6px;"
                         "background:#0f3460;display:flex;align-items:center;"
                         "justify-content:center;margin:0 auto 10px;"
                         "font-size:3rem}"
         ".disc-name{font-size:.8rem;color:#c8c8c8;word-break:break-all;"
                    "line-height:1.3}"
         ".badge{position:absolute;top:8px;right:8px;background:#2ecc71;"
                "color:#000;font-size:.65rem;font-weight:700;padding:2px 6px;"
                "border-radius:10px;text-transform:uppercase}"
         ".disc-num{position:absolute;top:8px;left:8px;background:#0f3460;"
                   "color:#888;font-size:.65rem;padding:2px 6px;border-radius:10px}"
         ".load-btn{display:block;width:100%%;margin-top:8px;padding:6px;"
                   "background:#0f3460;color:#c8a000;border:1px solid #c8a000;"
                   "border-radius:6px;cursor:pointer;font-size:.8rem;"
                   "transition:.15s}"
         ".load-btn:hover{background:#c8a000;color:#000}"
         ".load-btn.active{background:#2ecc71;color:#000;border-color:#2ecc71}"
         "@media(max-width:400px){.grid{grid-template-columns:repeat(2,1fr)}"
                                 ".disc-cover,.disc-cover-svg{width:120px;height:120px}}"
         ".pager{display:flex;align-items:center;justify-content:center;"
                "gap:16px;margin-top:24px;padding:12px}"
         ".pager-btn{background:#0f3460;color:#c8a000;border:1px solid #c8a000;"
                    "border-radius:6px;padding:8px 18px;cursor:pointer;font-size:.9rem;"
                    "transition:.15s}"
         ".pager-btn:hover:not(:disabled){background:#c8a000;color:#000}"
         ".pager-btn:disabled{opacity:.3;cursor:not-allowed}"
         ".pager-info{color:#888;font-size:.85rem}"
         "</style></head><body>");

    HCAT("<h1>💿 Nebula32, a CD32 Optical Drive Emulator</h1>"
         "<p class='subtitle'>%s &nbsp;·&nbsp; IP: %s &nbsp;·&nbsp; "
         "Use rotary encoder or click below to load a disc</p>",
         s_host, s_ip_str);

    // Status bar
    uint32_t page_num   = s_ws_page_offset / 64 + 1;
    uint32_t page_total = s_ws_total_count ? (s_ws_total_count + 63) / 64 : 1;
    bool     has_prev   = (s_ws_page_offset > 0);
    bool     has_next   = (s_ws_page_offset + s_ws_page_count < s_ws_total_count);

    HCAT("<div class='status'>"
         "<div class='status-item'>"
         "<span class='status-label'>Drive State</span>"
         "<span class='status-value'>%s</span></div>",
         state_name(commo_bridge_get_drive_state()));

    if (s_loaded_index < s_image_count) {
        char base[MAX_PATH_LEN];
        const char *loaded_name = s_image_paths[s_loaded_index];
        const char *sl = strrchr(loaded_name, '/');
        strncpy(base, sl ? sl + 1 : loaded_name, sizeof(base) - 1);
        HCAT("<div class='status-item'>"
             "<span class='status-label'>Loaded Disc</span>"
             "<span class='status-value'>%s</span></div>", base);
    }

    HCAT("<div class='status-item'>"
         "<span class='status-label'>Images</span>"
         "<span class='status-value'>%lu total</span></div>",
         (unsigned long)s_ws_total_count);

    if (page_total > 1) {
        HCAT("<div class='status-item'>"
             "<span class='status-label'>Page</span>"
             "<span class='status-value'>%lu / %lu</span></div>",
             (unsigned long)page_num, (unsigned long)page_total);
    }

    uint64_t sd_used = 0, sd_total = 0;
    if (sd_get_space(&sd_used, &sd_total)) {
        char used_str[16], total_str[16];
        fmt_bytes(used_str, sizeof(used_str), sd_used);
        fmt_bytes(total_str, sizeof(total_str), sd_total);
        HCAT("<div class='status-item'>"
             "<span class='status-label'>SD Card</span>"
             "<span class='status-value'>%s used / %s</span></div>",
             used_str, total_str);
    }

    HCAT("</div>");

    // Disc grid — populate cover cache once per render to avoid repeated f_stat
    if (!s_cover_cache_valid) refresh_cover_cache();

    HCAT("<div class='grid'>");

    for (uint32_t i = 0; i < s_image_count && i < 99; i++) {
        char base[MAX_PATH_LEN];
        basename_no_ext(s_image_paths[i], base, sizeof(base));
        // HTML-escape the filename before injecting into HTML/attribute context
        char base_esc[512];
        html_escape(base_esc, sizeof(base_esc), base);
        bool is_loaded = (i == s_loaded_index);

        const char *cover_path  = (i < WS_MAX_IMAGES) ? s_cover_cache[i] : "";
        bool        has_cover   = cover_path[0] != '\0' && cover_path[0] != '\1';

        HCAT("<div class='disc%s' onclick='loadDisc(%lu)'>",
             is_loaded ? " loaded" : "", (unsigned long)i);
        HCAT("<span class='disc-num'>%lu</span>", (unsigned long)(i + 1));
        if (is_loaded) HCAT("<span class='badge'>&#9658; Playing</span>");

        if (has_cover) {
            // Serve cover via /covers/ API endpoint
            HCAT("<img class='disc-cover' src='/covers/%s' "
                 "onerror=\"this.style.display='none'\" "
                 "alt='%s cover' loading='lazy'>", base_esc, base_esc);
        } else {
            HCAT("<div class='disc-cover-svg'>&#128192;</div>");
        }

        HCAT("<div class='disc-name'>%s</div>", base_esc);
        HCAT("<button class='load-btn%s' onclick='event.stopPropagation();loadDisc(%lu)'>"
             "%s</button>",
             is_loaded ? " active" : "",
             (unsigned long)i,
             is_loaded ? "✓ Loaded" : "Load");
        HCAT("</div>");  // .disc
    }

    HCAT("</div>");  // .grid

    // Pager (only shown when there is more than one page)
    if (page_total > 1) {
        HCAT("<div class='pager'>"
             "<button class='pager-btn' onclick='changePage(-1)' %s>&#8592; Prev</button>"
             "<span class='pager-info'>Showing %lu&ndash;%lu of %lu images</span>"
             "<button class='pager-btn' onclick='changePage(1)' %s>Next &#8594;</button>"
             "</div>",
             has_prev ? "" : "disabled",
             (unsigned long)(s_ws_page_offset + 1),
             (unsigned long)(s_ws_page_offset + s_ws_page_count),
             (unsigned long)s_ws_total_count,
             has_next ? "" : "disabled");
    }

    // Carousel / playlist controls (Phase 3b polish)
    HCAT("<details open style='margin:12px 0;padding:10px;background:#16213e;"
         "border:1px solid #0f3460;border-radius:8px;'>"
         "<summary style='cursor:pointer;color:#e94560;font-weight:bold;"
         "user-select:none'>&#127925; Carousel &amp; Playlists</summary>"
         "<div style='margin-top:10px;display:flex;gap:8px;align-items:center;"
         "flex-wrap:wrap;'>"
         "<button onclick='carousel(-1)' style='padding:6px 12px;background:#0f3460;"
         "color:#fff;border:none;border-radius:4px;cursor:pointer;'>"
         "&#8592; Prev disc</button>"
         "<button onclick='carousel(1)' style='padding:6px 12px;background:#0f3460;"
         "color:#fff;border:none;border-radius:4px;cursor:pointer;'>"
         "Next disc &#8594;</button>"
         "<select id='pl-sel' style='flex:1;min-width:120px;padding:6px;"
         "background:#1a1a2e;color:#e0e0e0;border:1px solid #0f3460;"
         "border-radius:4px;'>"
         "<option value=''>All discs</option>"
         "</select>"
         "<button onclick='setPlaylist()' style='padding:6px 12px;background:#e94560;"
         "color:#fff;border:none;border-radius:4px;cursor:pointer;'>Apply</button>"
         "</div>"
         "<p id='pl-msg' style='margin:6px 0 0;font-size:.85em;color:#aaa;'></p>"
         "</details>");

    // Firmware update section
    HCAT("<details style='margin:12px 0;padding:10px;background:#16213e;"
         "border:1px solid #0f3460;border-radius:8px;'>"
         "<summary style='cursor:pointer;color:#e94560;font-weight:bold;"
         "user-select:none'>&#128268; Firmware Update</summary>"
         "<div style='margin-top:10px;display:flex;gap:8px;align-items:center;'>"
         "<select id='fw-sel' style='flex:1;padding:6px;background:#1a1a2e;"
         "color:#e0e0e0;border:1px solid #0f3460;border-radius:4px;'>"
         "<option value=''>-- loading --</option>"
         "</select>"
         "<button onclick='flashFw()'"
         " style='padding:6px 14px;background:#e94560;color:#fff;"
         "border:none;border-radius:4px;cursor:pointer;'>"
         "Flash &amp; Reboot"
         "</button>"
         "</div>"
         "<p id='fw-msg' style='margin:6px 0 0;font-size:.85em;color:#aaa;'></p>"
         "</details>");

    // JavaScript
    HCAT("<script>"
         "function changePage(delta){"
         "  fetch('/api/page/'+(delta>0?'next':'prev'),{method:'POST'})"
         "  .then(r=>r.json()).then(d=>{if(d.ok)location.reload();})"
         "  .catch(e=>console.error(e));"
         "}"
         "function loadDisc(idx){"
         "  fetch('/api/load/'+idx,{method:'POST'})"
         "  .then(r=>r.json())"
         "  .then(d=>{if(d.ok){"
         "    document.querySelectorAll('.disc').forEach((el,i)=>{"
         "      el.classList.toggle('loaded',i===idx);"
         "      const btn=el.querySelector('.load-btn');"
         "      btn.textContent=i===idx?'✓ Loaded':'Load';"
         "      btn.classList.toggle('active',i===idx);"
         "      const badge=el.querySelector('.badge');"
         "      if(badge){badge.remove();}"
         "      if(i===idx){"
         "        const b=document.createElement('span');"
         "        b.className='badge';b.textContent='▶ Playing';el.appendChild(b);"
         "      }"
         "    });"
         "  }})"
         "  .catch(e=>console.error(e));"
         "}"
         /* Carousel: advance to next/prev disc in the active carousel */
         "function carousel(dir){"
         "  fetch('/api/carousel/'+(dir>0?'next':'prev'),{method:'POST'})"
         "  .then(function(r){return r.json();})"
         "  .then(function(d){if(d.ok)setTimeout(function(){location.reload();},400);})"
         "  .catch(function(e){console.error(e);});"
         "}"
         /* Playlist selector — populate from /api/playlist/list, no innerHTML */
         "(function(){"
         "var sel=document.getElementById('pl-sel');"
         "fetch('/api/playlist/list').then(function(r){return r.json();})"
         ".then(function(d){"
         "  if(!d.playlists)return;"
         "  d.playlists.forEach(function(p){"
         "    var o=document.createElement('option');"
         "    o.value=p;o.textContent=p;sel.appendChild(o);});"
         "}).catch(function(){});"
         "})();"
         "function setPlaylist(){"
         "  var name=document.getElementById('pl-sel').value;"
         "  var msg=document.getElementById('pl-msg');"
         "  var url=name===''?'/api/playlist/all':"
         "    '/api/playlist/set/'+encodeURIComponent(name);"
         "  msg.textContent='Switching…';"
         "  fetch(url,{method:'POST'}).then(function(r){return r.json();})"
         "  .then(function(d){"
         "    msg.textContent=d.ok?('Active: '+(name||'all discs')):"
         "      ('Error: '+(d.error||'unknown'));"
         "    if(d.ok)setTimeout(function(){location.reload();},500);"
         "  }).catch(function(){msg.textContent='No response.';});"
         "}"
         /* Firmware update helpers — safe DOM, no innerHTML */
         "(function(){"
         "var sel=document.getElementById('fw-sel');"
         "var msg=document.getElementById('fw-msg');"
         "fetch('/api/fw/list').then(function(r){return r.json();})"
         ".then(function(d){"
         "  sel.textContent='';"
         "  if(!d.files||!d.files.length){"
         "    var o=document.createElement('option');"
         "    o.textContent='No .uf2 files found';"
         "    sel.appendChild(o);return;}"
         "  d.files.forEach(function(f){"
         "    var o=document.createElement('option');"
         "    o.value=f;o.textContent=f;sel.appendChild(o);});"
         "}).catch(function(){"
         "  sel.textContent='';"
         "  var o=document.createElement('option');"
         "  o.textContent='SD not ready';sel.appendChild(o);});"
         "})();"
         "function flashFw(){"
         "  var name=document.getElementById('fw-sel').value;"
         "  var msg=document.getElementById('fw-msg');"
         "  if(!name||name===''||!confirm('Flash '+name+' and reboot?'))return;"
         "  msg.textContent='Flashing… do not power off.';"
         "  fetch('/api/fw/flash/'+encodeURIComponent(name),"
         "    {method:'POST',headers:{'X-FW-Token':'%s'}})"
         "  .then(function(r){return r.json();})"
         "  .then(function(d){"
         "    if(d.ok){"
         "      var h=document.createElement('h2');"
         "      h.textContent='Flashing… device will reboot in a few seconds.';"
         "      document.body.textContent='';"
         "      document.body.appendChild(h);"
         "    } else {"
         "      msg.textContent='Error: '+(d.error||'unknown');}"
         "  }).catch(function(){msg.textContent='No response — device may be rebooting.';});"
         "}"
         "</script>", s_fw_token);

    // Perspective starfield — 150 stars in normalised 3D space.
    // Each frame z decreases (star approaches); projected with x/z * W + cx.
    // Stars that reach z<=0 or fly off-screen are recycled at z=1 (far away).
    HCAT("<script>"
         "(function(){"
         "var c=document.createElement('canvas');"
         "c.style.cssText='position:fixed;top:0;left:0;width:100%%;height:100%%;z-index:-1;pointer-events:none';"
         "document.body.appendChild(c);"
         "var ctx=c.getContext('2d'),W,H,N=150,stars=[];"
         "function resize(){"
         "W=c.width=innerWidth;H=c.height=innerHeight;"
         "ctx.fillStyle='#1a1a2e';ctx.fillRect(0,0,W,H);}"
         "window.addEventListener('resize',resize);resize();"
         "function mk(){return{x:Math.random()-.5,y:Math.random()-.5,z:Math.random()*.9+.1};}"
         "for(var i=0;i<N;i++)stars.push(mk());"
         "function frame(){"
         "ctx.fillStyle='rgba(26,26,46,.2)';ctx.fillRect(0,0,W,H);"
         "var cx=W/2,cy=H/2;"
         "for(var i=0;i<N;i++){"
         "var s=stars[i];"
         "s.z-=.004;"
         "if(s.z<=0){stars[i]=mk();continue;}"
         "var px=s.x/s.z*W+cx,py=s.y/s.z*H+cy;"
         "if(px<0||px>W||py<0||py>H){stars[i]=mk();continue;}"
         "ctx.fillStyle='rgba(255,255,255,'+(1-s.z*.5)+')';"
         "ctx.beginPath();ctx.arc(px,py,Math.max(.2,(1-s.z)*2.5),0,6.28);ctx.fill();}"
         "requestAnimationFrame(frame);}"
         "frame();"
         "})();"
         "</script>");

    HCAT("</body></html>");
    return html;
#undef HCAT
}

#ifdef WEBSERVER_TEST_BUILD
// Expose build_html_page() to the host test suite.
// Only compiled when building with -DWEBSERVER_TEST_BUILD.
const char *webserver_get_page_for_test(void) { return build_html_page(); }
#endif

// ---------------------------------------------------------------------------
// Build JSON status response
// ---------------------------------------------------------------------------
static void build_json_status(char *buf, int bufsz) {
    char loaded_name[128] = "none";
    if (s_loaded_index < s_image_count) {
        const char *p = s_image_paths[s_loaded_index];
        const char *sl = strrchr(p, '/');
        strncpy(loaded_name, sl ? sl + 1 : p, sizeof(loaded_name) - 1);
    }

    char loaded_esc[128];
    json_escape(loaded_esc, sizeof(loaded_esc), loaded_name);

    int pos = snprintf(buf, bufsz,
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: application/json\r\n"
        "Connection: close\r\n\r\n"
        "{\"ok\":true,\"state\":\"%s\",\"state_id\":%d,"
        "\"loaded_index\":%lu,\"loaded_name\":\"%s\","
        "\"image_count\":%lu,\"ip\":\"%s\"",
        state_name(commo_bridge_get_drive_state()), commo_bridge_get_drive_state(),
        (unsigned long)s_loaded_index, loaded_esc,
        (unsigned long)s_image_count, s_ip_str);

    uint64_t sd_used = 0, sd_total = 0;
    if (sd_get_space(&sd_used, &sd_total)) {
        snprintf(buf + pos, bufsz - pos,
            ",\"sd_used_mb\":%lu,\"sd_total_mb\":%lu"
            ",\"page_offset\":%lu,\"page_count\":%lu,\"total_count\":%lu}",
            (unsigned long)(sd_used  / (1024 * 1024)),
            (unsigned long)(sd_total / (1024 * 1024)),
            (unsigned long)s_ws_page_offset,
            (unsigned long)s_ws_page_count,
            (unsigned long)s_ws_total_count);
    } else {
        snprintf(buf + pos, bufsz - pos,
            ",\"page_offset\":%lu,\"page_count\":%lu,\"total_count\":%lu}",
            (unsigned long)s_ws_page_offset,
            (unsigned long)s_ws_page_count,
            (unsigned long)s_ws_total_count);
    }
}

// ---------------------------------------------------------------------------
// Handle HTTP request line
// ---------------------------------------------------------------------------
// Returns the response as a static buffer or NULL to stream a file.
// 'conn' holds the accumulated request.

// S3: constant-time 33-byte token comparison (including NUL) to prevent
// timing-oracle attacks on the firmware-flash authorisation token.
static bool token_equal_ct(const char *a, const char *b) {
    unsigned int diff = 0;
    for (int i = 0; i < 33; i++)
        diff |= (unsigned char)a[i] ^ (unsigned char)b[i];
    return diff == 0;
}

static void handle_request(struct tcp_pcb *pcb, http_conn_t *conn) {
    char *req   = conn->request;
    bool  is_get  = (strncmp(req, "GET ",  4) == 0);
    bool  is_post = (strncmp(req, "POST ", 5) == 0);
    if (!is_get && !is_post) {
        static const char *m405 =
            "HTTP/1.1 405 Method Not Allowed\r\n"
            "Allow: GET, POST\r\nConnection: close\r\n\r\n";
        wolfSSL_write(conn->ssl, m405, (int)strlen(m405));
        return;
    }
    char *path_start = req + (is_get ? 4 : 5);
    char  path[256]  = "";

    // Extract URL path (up to space or \r\n)
    int i = 0;
    while (path_start[i] && path_start[i] != ' ' && path_start[i] != '\r'
           && i < 255) {
        path[i] = path_start[i];
        i++;
    }
    path[i] = '\0';

    LOG_INFO_MSG("HTTP", "%s %s", is_get ? "GET" : "POST", path);

    // ── GET / ── Main HTML page
    if (is_get && (strcmp(path, "/") == 0 || strcmp(path, "/index.html") == 0)) {
        const char *html = build_html_page();
        int total = (int)strlen(html);
        int sent  = 0;
        while (sent < total) {
            int chunk = total - sent;
            if (chunk > 4096) chunk = 4096;
            int wr;
            int retries = 0;
            do {
                wr = wolfSSL_write(conn->ssl, html + sent, chunk);
                if (wr <= 0) {
                    if (wolfSSL_get_error(conn->ssl, wr) != WOLFSSL_ERROR_WANT_WRITE)
                        goto html_done;
                    cyw43_arch_poll();
                }
            } while (wr <= 0 && ++retries < 20);
            if (wr <= 0) break;
            sent += wr;
        }
        html_done:;
        return;
    }

    // ── GET /api/status ── JSON status
    if (is_get && strcmp(path, "/api/status") == 0) {
        build_json_status(conn->resp_buf, sizeof(conn->resp_buf));
        wolfSSL_write(conn->ssl, conn->resp_buf, (int)strlen(conn->resp_buf));
        return;
    }

    // ── GET /api/images ── JSON image list
    if (is_get && strcmp(path, "/api/images") == 0) {
        int pos = snprintf(conn->resp_buf, sizeof(conn->resp_buf),
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n"
            "Connection: close\r\n\r\n[");
        for (uint32_t j = 0; j < s_image_count && j < 99; j++) {
            char base[MAX_PATH_LEN], base_esc[256], cp[256] = "";
            basename_no_ext(s_image_paths[j], base, sizeof(base));
            json_escape(base_esc, sizeof(base_esc), base);
            bool hc = cover_exists(s_image_paths[j], cp, sizeof(cp));
            pos += snprintf(conn->resp_buf + pos, sizeof(conn->resp_buf) - pos,
                "%s{\"index\":%lu,\"name\":\"%s\",\"has_cover\":%s,\"loaded\":%s}",
                j > 0 ? "," : "",
                (unsigned long)j, base_esc,
                hc ? "true" : "false",
                (j == s_loaded_index) ? "true" : "false");
        }
        pos += snprintf(conn->resp_buf + pos, sizeof(conn->resp_buf) - pos, "]");
        wolfSSL_write(conn->ssl, conn->resp_buf, pos);
        return;
    }

    // ── POST /api/load/{index} ── Load a disc
    if (is_post && strncmp(path, "/api/load/", 10) == 0) {
        char *endp;
        unsigned long idx_ul = strtoul(path + 10, &endp, 10);
        uint32_t idx = (endp == path + 10 || idx_ul > UINT32_MAX) ? UINT32_MAX : (uint32_t)idx_ul;
        if (idx < s_image_count) {
            s_load_index   = idx;
            s_load_pending = true;
            LOG_INFO_MSG("HTTP", "web load request: image %lu", (unsigned long)idx);
            snprintf(conn->resp_buf, sizeof(conn->resp_buf),
                "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n"
                "Connection: close\r\n\r\n"
                "{\"ok\":true,\"index\":%lu}", (unsigned long)idx);
        } else {
            snprintf(conn->resp_buf, sizeof(conn->resp_buf),
                "HTTP/1.1 400 Bad Request\r\nContent-Type: application/json\r\n"
                "Connection: close\r\n\r\n"
                "{\"ok\":false,\"error\":\"index out of range\"}");
        }
        wolfSSL_write(conn->ssl, conn->resp_buf, (int)strlen(conn->resp_buf));
        return;
    }

    // ── POST /api/page/next or /api/page/prev ── Paginate image list
    if (is_post && strcmp(path, "/api/page/next") == 0) {
        s_page_delta   = +1;
        s_page_request = true;
        snprintf(conn->resp_buf, sizeof(conn->resp_buf),
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n"
            "Connection: close\r\n\r\n{\"ok\":true,\"direction\":\"next\"}");
        wolfSSL_write(conn->ssl, conn->resp_buf, (int)strlen(conn->resp_buf));
        return;
    }
    if (is_post && strcmp(path, "/api/page/prev") == 0) {
        s_page_delta   = -1;
        s_page_request = true;
        snprintf(conn->resp_buf, sizeof(conn->resp_buf),
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n"
            "Connection: close\r\n\r\n{\"ok\":true,\"direction\":\"prev\"}");
        wolfSSL_write(conn->ssl, conn->resp_buf, (int)strlen(conn->resp_buf));
        return;
    }

    // ── POST /api/eject ── Eject disc
    if (is_post && strcmp(path, "/api/eject") == 0) {
        s_load_index   = UINT32_MAX;
        s_load_pending = true;
        snprintf(conn->resp_buf, sizeof(conn->resp_buf),
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n"
            "Connection: close\r\n\r\n{\"ok\":true}");
        wolfSSL_write(conn->ssl, conn->resp_buf, (int)strlen(conn->resp_buf));
        return;
    }

    // ── POST /api/carousel/next | /api/carousel/prev ── advance the carousel
    if (is_post && strcmp(path, "/api/carousel/next") == 0) {
        s_carousel_delta = +1; s_carousel_request = true;
        snprintf(conn->resp_buf, sizeof(conn->resp_buf),
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n"
            "Connection: close\r\n\r\n{\"ok\":true,\"direction\":\"next\"}");
        wolfSSL_write(conn->ssl, conn->resp_buf, (int)strlen(conn->resp_buf));
        return;
    }
    if (is_post && strcmp(path, "/api/carousel/prev") == 0) {
        s_carousel_delta = -1; s_carousel_request = true;
        snprintf(conn->resp_buf, sizeof(conn->resp_buf),
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n"
            "Connection: close\r\n\r\n{\"ok\":true,\"direction\":\"prev\"}");
        wolfSSL_write(conn->ssl, conn->resp_buf, (int)strlen(conn->resp_buf));
        return;
    }

    // ── POST /api/playlist/all ── switch carousel back to all discs
    if (is_post && strcmp(path, "/api/playlist/all") == 0) {
        s_playlist_name[0] = '\0';      // "" = all discs
        s_playlist_request = true;
        snprintf(conn->resp_buf, sizeof(conn->resp_buf),
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n"
            "Connection: close\r\n\r\n{\"ok\":true,\"source\":\"all\"}");
        wolfSSL_write(conn->ssl, conn->resp_buf, (int)strlen(conn->resp_buf));
        return;
    }

    // ── POST /api/playlist/set/{name} ── activate playlist <name>.m3u
    // {name} becomes part of a file path (0:/playlists/<name>.m3u), so it is
    // validated against path-traversal: no '/', '\\', or ".." and length-bounded.
    if (is_post && strncmp(path, "/api/playlist/set/", 18) == 0) {
        const char *name = path + 18;
        size_t nlen = strlen(name);
        bool safe = (nlen > 0 && nlen < sizeof(s_playlist_name) &&
                     !strchr(name, '/') && !strchr(name, '\\') && !strstr(name, ".."));
        if (!safe) {
            snprintf(conn->resp_buf, sizeof(conn->resp_buf),
                "HTTP/1.1 400 Bad Request\r\nContent-Type: application/json\r\n"
                "Connection: close\r\n\r\n{\"ok\":false,\"error\":\"bad name\"}");
        } else {
            snprintf(s_playlist_name, sizeof(s_playlist_name), "%s", name);
            s_playlist_request = true;
            snprintf(conn->resp_buf, sizeof(conn->resp_buf),
                "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n"
                "Connection: close\r\n\r\n{\"ok\":true}");
        }
        wolfSSL_write(conn->ssl, conn->resp_buf, (int)strlen(conn->resp_buf));
        return;
    }

    // ── GET /api/playlist/list ── List .m3u playlists in 0:/playlists/
    // Names are returned base-only (no dir, no ".m3u") so each maps directly to
    // POST /api/playlist/set/{name}.  A missing playlists dir yields [].
    if (is_get && strcmp(path, "/api/playlist/list") == 0) {
        static char pl_paths[8][MAX_PATH_LEN];  // off the lwIP callback stack
        uint32_t n = sd_scan_m3u_files(pl_paths, 8, "0:/playlists/", 0);
        int pos = snprintf(conn->resp_buf, sizeof(conn->resp_buf),
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n"
            "Connection: close\r\n\r\n{\"playlists\":[");
        for (uint32_t j = 0; j < n && pos < (int)sizeof(conn->resp_buf) - 4; j++) {
            char base[MAX_PATH_LEN];
            basename_no_ext(pl_paths[j], base, sizeof(base));
            char esc[MAX_PATH_LEN * 2];
            json_escape(esc, sizeof(esc), base);
            pos += snprintf(conn->resp_buf + pos, sizeof(conn->resp_buf) - pos,
                "%s\"%s\"", j ? "," : "", esc);
        }
        snprintf(conn->resp_buf + pos, sizeof(conn->resp_buf) - pos, "]}");
        wolfSSL_write(conn->ssl, conn->resp_buf, (int)strlen(conn->resp_buf));
        return;
    }

    // ── GET /api/fw/list ── List .uf2 firmware files on SD root
    if (is_get && strcmp(path, "/api/fw/list") == 0) {
        static char fw_paths[8][MAX_PATH_LEN];  // O1: 2 KB off the lwIP callback stack
        uint32_t n = sd_scan_uf2_files(fw_paths, 8, "0:/", 0);
        int pos = snprintf(conn->resp_buf, sizeof(conn->resp_buf),
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n"
            "Connection: close\r\n\r\n{\"files\":[");
        for (uint32_t j = 0; j < n && pos < (int)sizeof(conn->resp_buf) - 4; j++) {
            // Strip the "0:/" prefix for the client
            const char *name = fw_paths[j];
            if (name[0] == '0' && name[1] == ':' && name[2] == '/') name += 3;
            char esc[MAX_PATH_LEN * 2];
            json_escape(esc, sizeof(esc), name);
            pos += snprintf(conn->resp_buf + pos, sizeof(conn->resp_buf) - pos,
                "%s\"%s\"", j ? "," : "", esc);
        }
        snprintf(conn->resp_buf + pos, sizeof(conn->resp_buf) - pos, "]}");
        wolfSSL_write(conn->ssl, conn->resp_buf, (int)strlen(conn->resp_buf));
        return;
    }

    // ── POST /api/fw/flash/{filename} ── Validate + flash UF2 from SD root
    if (is_post && strncmp(path, "/api/fw/flash/", 14) == 0) {
        // Validate firmware-flash token before doing anything else.
        char provided_token[33] = "";
        extract_request_token(req, path, provided_token, sizeof(provided_token));
        if (s_fw_token[0] == '\0' || !token_equal_ct(provided_token, s_fw_token)) {
            static const char *unauth =
                "HTTP/1.1 403 Forbidden\r\nContent-Type: application/json\r\n"
                "Connection: close\r\n\r\n"
                "{\"ok\":false,\"error\":\"invalid or missing fw_token\"}";
            wolfSSL_write(conn->ssl, unauth, (int)strlen(unauth));
            return;
        }

        // Strip query string from fname before filename validation.
        const char *fname_raw = path + 14;
        char fname[MAX_PATH_LEN];
        size_t fn_max = sizeof(path) - 14U - 1U; // bytes remaining in path[] after prefix
        size_t fn_len = 0;
        while (fname_raw[fn_len] && fname_raw[fn_len] != '?' && fn_len < fn_max)
            fn_len++;
        memcpy(fname, fname_raw, fn_len);
        fname[fn_len] = '\0';

        // Bounds first (cheapest checks), then string content.
        // Blocks: empty, oversized (headroom for "0:/" prefix), path traversal (..),
        // path separators (/ and \), and percent-encoded sequences (%2e%2e bypasses
        // the ".." check — same defence as the /covers/ endpoint).
        if (fn_len == 0 || fn_len >= (size_t)(MAX_PATH_LEN - 3) ||
            strstr(fname, "..") || strchr(fname, '/') ||
            strchr(fname, '\\') || strchr(fname, '%')) {
            static const char *bad =
                "HTTP/1.1 400 Bad Request\r\nContent-Type: application/json\r\n"
                "Connection: close\r\n\r\n{\"ok\":false,\"error\":\"invalid filename\"}";
            wolfSSL_write(conn->ssl, bad, (int)strlen(bad));
            return;
        }
        char full_path[3 + MAX_PATH_LEN + 1];
        snprintf(full_path, sizeof(full_path), "0:/%s", fname);
        // Acknowledge before the blocking flash operation; tcp_output flushes it
        static const char *ack =
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n"
            "Connection: close\r\n\r\n{\"ok\":true,\"msg\":\"flashing\"}";
        wolfSSL_write(conn->ssl, ack, (int)strlen(ack));
        tcp_output(pcb);   // flush ack immediately — reboot follows
        // fw_flash_and_reboot never returns on success; returns error code on failure
        fw_result_t fr = fw_flash_and_reboot(full_path);
        snprintf(conn->resp_buf, sizeof(conn->resp_buf),
            "HTTP/1.1 500 Internal Server Error\r\n"
            "Content-Type: application/json\r\n"
            "Connection: close\r\n\r\n{\"ok\":false,\"error\":\"%s\"}",
            fw_result_str(fr));
        wolfSSL_write(conn->ssl, conn->resp_buf, (int)strlen(conn->resp_buf));
        return;
    }

    // ── GET /covers/{name}.jpg ── Serve cover art from SD card
    if (is_get && strncmp(path, "/covers/", 8) == 0) {
        // Sanitise: only a bare filename is permitted — no path separators,
        // no "..", and no percent-encoded sequences (%2e%2e bypasses ".." check).
        const char *cover_name = path + 8;
        if (strstr(cover_name, "..") || strchr(cover_name, '/') ||
            strchr(cover_name, '\\') || strchr(cover_name, '%')) {
            static const char *forbidden =
                "HTTP/1.1 403 Forbidden\r\nConnection: close\r\n\r\n";
            wolfSSL_write(conn->ssl, forbidden, (int)strlen(forbidden));
            return;
        }

        char sd_path[264];
        snprintf(sd_path, sizeof(sd_path), "0:/covers/%s", cover_name);

        FIL cover_file;
        FRESULT fr = f_open(&cover_file, sd_path, FA_READ);
        if (fr == FR_OK) {
            FSIZE_t fsize = f_size(&cover_file);
            // Send HTTP header
            int hlen = snprintf(conn->resp_buf, sizeof(conn->resp_buf),
                "HTTP/1.1 200 OK\r\n"
                "Content-Type: image/jpeg\r\n"
                "Content-Length: %lu\r\n"
                "Cache-Control: max-age=3600\r\n"
                "Connection: close\r\n\r\n",
                (unsigned long)fsize);
            wolfSSL_write(conn->ssl, conn->resp_buf, hlen);

            // Stream file in 512-byte chunks; retry on WANT_WRITE (TLS send buffer full)
            static uint8_t chunk[512];
            UINT br;
            while (f_read(&cover_file, chunk, sizeof(chunk), &br) == FR_OK && br > 0) {
                int wr = WOLFSSL_FATAL_ERROR;
                for (int retries = 0; retries < 20 && wr <= 0; retries++) {
                    wr = wolfSSL_write(conn->ssl, chunk, (int)br);
                    if (wr <= 0) {
                        int we = wolfSSL_get_error(conn->ssl, wr);
                        if (we != WOLFSSL_ERROR_WANT_WRITE) goto cover_done;
                        cyw43_arch_poll();
                    }
                }
                if (wr <= 0) break;
            }
            cover_done:
            f_close(&cover_file);
            return;
        }

        // Cover not found — return 404 with generic CD SVG
        static const char *not_found =
            "HTTP/1.1 404 Not Found\r\n"
            "Content-Type: image/svg+xml\r\n"
            "Cache-Control: max-age=60\r\n"
            "Connection: close\r\n\r\n"
            "<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200'>"
            "<rect width='200' height='200' fill='#0f3460' rx='8'/>"
            "<circle cx='100' cy='100' r='75' fill='#1a1a4e' stroke='#c8a000' stroke-width='2'/>"
            "<circle cx='100' cy='100' r='15' fill='#0f3460' stroke='#888' stroke-width='1'/>"
            "<text x='100' y='170' text-anchor='middle' fill='#888' "
            "font-family='system-ui' font-size='12'>No Cover Art</text>"
            "</svg>";
        wolfSSL_write(conn->ssl, not_found, (int)strlen(not_found));
        return;
    }

    // ── 404 fallback ──
    // Sanitise path: strip non-printable bytes before reflecting into response.
    char safe_path[256];
    size_t sp = 0;
    for (const char *c = path; *c && sp < sizeof(safe_path) - 1; c++)
        safe_path[sp++] = (*c >= 0x20 && *c < 0x7f) ? *c : '?';
    safe_path[sp] = '\0';
    snprintf(conn->resp_buf, sizeof(conn->resp_buf),
        "HTTP/1.1 404 Not Found\r\nContent-Type: text/plain\r\n"
        "Connection: close\r\n\r\nNot found: %s", safe_path);
    wolfSSL_write(conn->ssl, conn->resp_buf, (int)strlen(conn->resp_buf));
}

// ---------------------------------------------------------------------------
// TLS receive callback — called by LwIPNativeReceiveCB after it buffers the pbuf.
// arg = conn (stored in nlwip->arg by wolfSSL_SetIO_LwIP).
// ---------------------------------------------------------------------------
static err_t tls_recv_fn(void *arg, struct tcp_pcb *pcb,
                          struct pbuf *p, err_t err) {
    http_conn_t *conn = (http_conn_t *)arg;

    if (!p || err != ERR_OK) {
        tcp_close(pcb);
        conn_free(conn);
        return ERR_OK;
    }

    // Advance receive window. LwIPNativeReceiveCB only calls tcp_recved for
    // chained (2nd+) pbufs — we must cover the first pbuf here.
    tcp_recved(pcb, p->tot_len);

    // Phase 1: drive TLS handshake until WOLFSSL_SUCCESS.
    // wolfSSL_accept is non-blocking; WANT_READ means come back when more data arrives.
    if (!conn->tls_ready) {
        int r = wolfSSL_accept(conn->ssl);
        if (r != WOLFSSL_SUCCESS) {
            int e = wolfSSL_get_error(conn->ssl, r);
            if (e == WOLFSSL_ERROR_WANT_READ || e == WOLFSSL_ERROR_WANT_WRITE)
                return ERR_OK;  // normal — wait for next packet
            printf("[WEB] TLS handshake error %d\n", e);
            tcp_close(pcb);
            conn_free(conn);
            return ERR_OK;
        }
        conn->tls_ready = true;
    }

    // Phase 2: handshake done — read plaintext HTTP request.
    int n = wolfSSL_read(conn->ssl,
                         conn->request + conn->req_len,
                         (int)sizeof(conn->request) - 1 - conn->req_len);
    if (n > 0) {
        conn->req_len += n;
        conn->request[conn->req_len] = '\0';
    }

    // Dispatch once we have a complete HTTP header.
    if (conn->req_len > 0 && strstr(conn->request, "\r\n\r\n")) {
        handle_request(pcb, conn);
        tcp_output(pcb);
        tcp_close(pcb);
        conn_free(conn);
    }
    return ERR_OK;
}

static err_t tcp_accept_cb(void *arg, struct tcp_pcb *new_pcb, err_t err) {
    (void)arg;
    if (err != ERR_OK || !new_pcb) return ERR_VAL;

    http_conn_t *conn = conn_alloc();
    if (!conn) {
        tcp_close(new_pcb);
        return ERR_MEM;
    }

    conn->ssl = wolfSSL_new(s_tls_ctx);
    if (!conn->ssl) {
        conn_free(conn);
        tcp_close(new_pcb);
        return ERR_MEM;
    }

    // wolfSSL_SetIO_LwIP installs LwIPNativeReceiveCB as the lwIP recv callback,
    // sets tcp_arg to &ssl->lwipCtx, and stores tls_recv_fn + conn in nlwip.
    wolfSSL_SetIO_LwIP(conn->ssl, new_pcb, tls_recv_fn, NULL, conn);
    tcp_setprio(new_pcb, TCP_PRIO_MIN);  // Low priority vs bus handler

    return ERR_OK;
}

// ---------------------------------------------------------------------------
// webserver_init
// ---------------------------------------------------------------------------
bool webserver_init(void) {
    read_wifi_config();

    if (s_ssid[0] == '\0') {
        printf("[WEB] No wifi_ssid in nebula32.cfg — WiFi disabled\n"
               "[WEB] Add these lines to enable:\n"
               "      wifi_ssid     = YourNetworkName\n"
               "      wifi_password = YourPassword\n");
        return false;
    }

    // Generate and persist a firmware-flash token if none is configured.
    // The token is appended to nebula32.cfg and visible to whoever has SD access.
#ifndef WEBSERVER_TEST_BUILD
    if (s_fw_token[0] == '\0') {
        generate_and_save_token();
        printf("[WEB] fw_token generated: %s\n"
               "[WEB] Copy this value from nebula32.cfg to authorise firmware flashing.\n",
               s_fw_token);
    }
#endif

    printf("[WEB] Connecting to WiFi SSID: %s ...\n", s_ssid);
    LOG_INFO_MSG("WEB ", "connecting to SSID: %s", s_ssid);

    // Initialise WiFi in poll mode (no RTOS required)
    if (cyw43_arch_init()) {
        printf("[WEB] CYW43 init failed\n");
        LOG_ERROR_MSG("WiFi CYW43 init failed");
        return false;
    }

    cyw43_arch_enable_sta_mode();

    // Connect (timeout: 30 seconds)
    if (cyw43_arch_wifi_connect_timeout_ms(s_ssid, s_pass,
                                            CYW43_AUTH_WPA2_AES_PSK,
                                            30000) != 0) {
        printf("[WEB] WiFi connection failed (wrong password or SSID?)\n");
        LOG_ERROR_MSG("WiFi connection failed (SSID=%s)", s_ssid);
        return false;
    }

    // Get IP address
    ip4_addr_t *ip = &cyw43_state.netif[0].ip_addr;
    snprintf(s_ip_str, sizeof(s_ip_str), "%s", ip4addr_ntoa(ip));
    printf("[WEB] Connected! IP: %s\n", s_ip_str);
    LOG_INFO_MSG("WEB ", "WiFi connected, IP=%s", s_ip_str);

    // wolfSSL deliberately uses the default SRAM heap, NOT psram_alloc:
    // the PSRAM bump allocator never reclaims (psram_free is a mark-only
    // no-op), but wolfSSL mallocs/frees on every TLS handshake — routing it
    // there leaked PSRAM per HTTPS connection until psram_alloc returned
    // NULL and TLS died.  If SRAM pressure returns, the correct fix is
    // WOLFSSL_STATIC_MEMORY with a fixed PSRAM arena that wolfSSL manages
    // internally — not wolfSSL_SetAllocators over the bump allocator.

    // Initialise wolfSSL TLS context (once per boot)
    wolfSSL_Init();
    s_tls_ctx = wolfSSL_CTX_new(wolfTLSv1_3_server_method());
    if (!s_tls_ctx) {
        printf("[WEB] wolfSSL_CTX_new failed\n");
        return false;
    }
    // Load TLS certificate — SD card takes priority; compiled-in cert is the fallback.
    // SD card paths: 0:/certs/nebula32.crt.der + 0:/certs/nebula32.key.der
    // Compiled-in fallback: include/tls_cert.h (regenerated by tools/gen_tls_cert.sh)
    {
        bool loaded = false;
#ifndef WEBSERVER_TEST_BUILD
        // Attempt to load user cert from SD card (reuse one buffer for cert then key).
        static uint8_t s_cert_buf[1024];
        FIL f; UINT br;
        bool cert_ok = false, key_ok = false;
        if (f_open(&f, "0:/certs/nebula32.crt.der", FA_READ) == FR_OK) {
            if (f_read(&f, s_cert_buf, sizeof(s_cert_buf), &br) == FR_OK && br > 0)
                cert_ok = wolfSSL_CTX_use_certificate_buffer(s_tls_ctx,
                    s_cert_buf, (long)br, SSL_FILETYPE_ASN1) == WOLFSSL_SUCCESS;
            f_close(&f);
        }
        if (cert_ok && f_open(&f, "0:/certs/nebula32.key.der", FA_READ) == FR_OK) {
            if (f_read(&f, s_cert_buf, sizeof(s_cert_buf), &br) == FR_OK && br > 0)
                key_ok = wolfSSL_CTX_use_PrivateKey_buffer(s_tls_ctx,
                    s_cert_buf, (long)br, SSL_FILETYPE_ASN1) == WOLFSSL_SUCCESS;
            f_close(&f);
        }
        if (cert_ok && key_ok) {
            printf("[WEB] TLS cert loaded from SD (0:/certs/nebula32.crt.der)\n");
            loaded = true;
        }
#endif
        if (!loaded) {
            // Compiled-in cert from tls_cert.h (self-signed, generated by tools/gen_tls_cert.sh).
            if (wolfSSL_CTX_use_certificate_buffer(s_tls_ctx,
                    server_ecc_der_256, (long)sizeof_server_ecc_der_256,
                    SSL_FILETYPE_ASN1) != WOLFSSL_SUCCESS ||
                wolfSSL_CTX_use_PrivateKey_buffer(s_tls_ctx,
                    ecc_key_der_256, (long)sizeof_ecc_key_der_256,
                    SSL_FILETYPE_ASN1) != WOLFSSL_SUCCESS) {
                printf("[WEB] TLS cert/key load failed\n");
                wolfSSL_CTX_free(s_tls_ctx);
                s_tls_ctx = NULL;
                return false;
            }
            printf("[WEB] TLS using compiled-in cert (copy certs/*.der to SD for custom cert)\n");
        }
    }

    // Start TLS listener on port 443
    s_listener = tcp_new_ip_type(IPADDR_TYPE_V4);
    if (!s_listener) return false;

    tcp_bind(s_listener, IP_ANY_TYPE, WS_HTTPS_PORT);
    s_listener = tcp_listen_with_backlog(s_listener, 4);
    tcp_accept(s_listener, tcp_accept_cb);

    s_running = true;
    printf("[WEB] HTTPS server running at https://%s/ (self-signed cert)\n", s_ip_str);
    printf("[WEB] Also try: https://%s.local/\n", s_host);
    LOG_INFO_MSG("WEB ", "HTTPS server listening on port %d", WS_HTTPS_PORT);

    return true;
}

// ---------------------------------------------------------------------------
// webserver_poll — call from Core 0 main loop
// ---------------------------------------------------------------------------
void webserver_poll(void) {
    if (!s_running) return;
    cyw43_arch_poll();
}

void webserver_notify_state_change(void) {
    s_cover_cache_valid = false;  // disc list may have changed; rebuild on next render
}

bool webserver_is_running(void) { return s_running; }
const char *webserver_get_ip(void) { return s_ip_str; }

bool webserver_has_load_request(void) {
    if (s_load_pending) {
        s_load_pending = false;
        return true;
    }
    return false;
}

uint32_t webserver_get_load_index(void) { return s_load_index; }

// Called by main.c after a disc is loaded to update the "loaded" badge
void webserver_set_loaded_index(uint32_t index) {
    s_loaded_index = index;
}

void webserver_set_page_info(uint32_t page_offset, uint32_t page_count,
                             uint32_t total_count) {
    s_ws_page_offset = page_offset;
    s_ws_page_count  = page_count;
    s_ws_total_count = total_count;
}

bool webserver_has_page_request(void) {
    if (s_page_request) { s_page_request = false; return true; }
    return false;
}

int webserver_get_page_delta(void) { return s_page_delta; }

bool webserver_has_carousel_request(void) {
    if (s_carousel_request) { s_carousel_request = false; return true; }
    return false;
}

int webserver_get_carousel_delta(void) { return s_carousel_delta; }

bool webserver_has_playlist_request(void) {
    if (s_playlist_request) { s_playlist_request = false; return true; }
    return false;
}

const char *webserver_get_playlist_name(void) { return s_playlist_name; }

#else // !PICO_CYW43_SUPPORTED — stub out the entire webserver for non-W builds

bool webserver_init(void) { return false; }
void webserver_poll(void) {}
void webserver_notify_state_change(void) {}
bool webserver_is_running(void) { return false; }
const char *webserver_get_ip(void) { return ""; }
bool webserver_has_load_request(void) { return false; }
uint32_t webserver_get_load_index(void) { return 0; }
void webserver_set_loaded_index(uint32_t index) { (void)index; }
void webserver_set_page_info(uint32_t a, uint32_t b, uint32_t c) { (void)a;(void)b;(void)c; }
bool webserver_has_page_request(void) { return false; }
int  webserver_get_page_delta(void)   { return 0; }
bool webserver_has_carousel_request(void) { return false; }
int  webserver_get_carousel_delta(void)   { return 0; }
bool webserver_has_playlist_request(void) { return false; }
const char *webserver_get_playlist_name(void) { return ""; }

#endif // PICO_CYW43_SUPPORTED
